#print(type("Hello World"))
#print(type(1))
#print(type(1.2))
#var = input("Give me a number : ")
#print(type(var))
#var = int(var)
#print(type(var))
#var = float(var)
#print(type(var))
var = int(input("Give me a number: "))
#print(type(var))
#print("My number was " + str(var))
print("My number was" , str(var))
